# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d7c978d2e9dbb0ca4ecd8947bed7c1413313958b4b4019234bcd12ea1b667b5d31aa37a43b5bb75c2b39541ebbf813d05bbd90334f3b3a3e552505a715d7cac

test:
  secret_key_base: 09dbc2f0d941185a786d7768e4581728a1e19b584e12d92be39804cd13077f119d17a9b61971c86e7bea3402e72c6eef4c023f080e22608c6e7dcec63821f6c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
